'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class EngResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Virus_Effect_Remover.EngResource", GetType(EngResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autorun.inf file has not been found.
        '''
        '''If you know you have an infected pendrive,
        '''insert it and rescan, after 10 seconds.
        '''
        '''Or scan manually for any file, using the
        '''&quot;I know this is a Virus: &quot; Box..
        '''</summary>
        Public Shared ReadOnly Property AutorunFoundMsg() As String
            Get
                Return ResourceManager.GetString("AutorunFoundMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adds V.E.R©. to the Windows® Startup list..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_AddStartup() As String
            Get
                Return ResourceManager.GetString("hlpcFA_AddStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows Autorun.inf file, &amp; any information about it&apos;s Status..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_AutorunBox1() As String
            Get
                Return ResourceManager.GetString("hlpcFA_AutorunBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blocks a known virus, once you have confirmed the
        '''correct information, from sources on the internet..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_BlockAVirusbutton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_BlockAVirusbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse to a Folder..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_BR2() As String
            Get
                Return ResourceManager.GetString("hlpcFA_BR2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse to the Folder, that you want to Scan..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_BrowseDir() As String
            Get
                Return ResourceManager.GetString("hlpcFA_BrowseDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse to the file(s) to Delete..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_BT1() As String
            Get
                Return ResourceManager.GetString("hlpcFA_BT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tick if you want to Delete all 
        '''Autorun.inf file, with just one click..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_CheckBox1() As String
            Get
                Return ResourceManager.GetString("hlpcFA_CheckBox1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tick this if you want to Delete the parent file of the process.
        '''
        '''Warning! Use extreme caution, when Deleting multiple files!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_CheckBox2() As String
            Get
                Return ResourceManager.GetString("hlpcFA_CheckBox2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.E.R.© will scan drives A: &amp; B:
        '''
        '''VSLab: Recommend, you ONLY turn this on,
        '''while you are scanning floppy diskettes..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_CheckBox4() As String
            Get
                Return ResourceManager.GetString("hlpcFA_CheckBox4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sets the V.E.R.© Process List, refresh interval..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_CheckBox6() As String
            Get
                Return ResourceManager.GetString("hlpcFA_CheckBox6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open the Command Prompt (CMD) Window..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_CommandPromptButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_CommandPromptButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show the file details, as per Windows® properties..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DDFileDetail() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DDFileDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete ALL files in this Folder! ! Warning!
        '''
        '''Use extreme Caution! When Deleting files..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_delAF() As String
            Get
                Return ResourceManager.GetString("hlpcFA_delAF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will Delete all empty folder(s) of current selected Folder..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DelAllEmptyDir() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DelAllEmptyDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.E.R.© will Delete any empty folder, if found in current location..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DelEmptyDir2() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DelEmptyDir2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deletes selected, file(s)..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DeleteFileInList() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DeleteFileInList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click, to Delete ALL files with specified extension(s)..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DelFileWithExt() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DelFileWithExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If this box is ticked, then V.E.R.© will
        '''NOT then popup, an exit confirmation box.
        '''
        '''Exit selection, happens immediately!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DisableExitDialog() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DisableExitDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Runs the DirectX Diagnostic Tool..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_DXDiagButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_DXDiagButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disable/Enable (On/Off) Windows® Autoplay files.
        '''
        '''Turns on or off the autoplay for inserted media.
        '''
        '''VSLab: Recommend that you turn Off &apos;Autoplay&apos;!
        '''See V.E.R.© Help or PDF file for more detail..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Enable_autorun() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Enable_autorun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repair Windows® MSConfig, &amp; then RUN it. 
        '''
        '''Use this Windows® tool, to modify your
        '''OS settings, for BOOTing and Startup..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_enable_msconfig() As String
            Get
                Return ResourceManager.GetString("hlpcFA_enable_msconfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repair Windows® Registry Editor, &amp; then RUN it. 
        '''
        '''Use this Windows® tool, to edit the registry. 
        '''Take great care, when editing the registry!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Enable_regedit() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Enable_regedit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repair Windows® Taskmanager, &amp; then RUN it. 
        '''
        '''Use this Windows® tool, to both view, &amp;/or 
        '''kill any suspect running processes. etc..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Enable_taskmgr() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Enable_taskmgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It is highly recommended that you Enable process filter!
        '''This protects the OS, from improper process termination..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_EnableProcessFilter() As String
            Get
                Return ResourceManager.GetString("hlpcFA_EnableProcessFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shutdown V.E.R.© ALL it&apos;s scans &amp; services, then EXIT..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_EndButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_EndButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add extension(s) of file[s] here.
        '''E.g. 
        '''
        '''.txt
        '''.bmp
        '''.mp3.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ExtBox() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ExtBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force Delete file(s) and folder(s) by gaining the NTFS
        '''Security, &amp; searching as module of any running process..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FDel() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applies the chosen attributes, to any selected file(s)..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FileAttributeApply() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FileAttributeApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display file extension with file name..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FileExt() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FileExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This list will display file(s) associated with 
        '''the Autorun.inf file, or the scanned file name..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FileFoundLV() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FileFoundLV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type the filename, which you think may be a virus..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Filenamebox() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Filenamebox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use File Protector popup, to set any type of file attribute.
        '''For protecting valuable files, by making them READ only. etc.
        '''
        '''Or this tool can be used to REMOVE file attributes, that you 
        '''DO NOT want on a file, or file(s), folder, or folder(s) etc..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FileProtectorButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FileProtectorButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add file(s) that should be Deleted, if and only 
        '''if, (IFF) they are in the selected folder..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FilesAllowedToDeleteBox() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FilesAllowedToDeleteBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disable/Enable Autorun.inf file(s) on devices.
        '''
        '''VSLab: Recommend that you Disable Autorun.inf!
        '''See V.E.R.© help or PDF file for more details..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_find_autorun() As String
            Get
                Return ResourceManager.GetString("hlpcFA_find_autorun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finds cloned copies of a virus, that you might have found,
        '''using V.E.R.© or anti-Virus/anti-Tojan tools that you have. 
        '''
        '''This will enable you to trace &amp; remove, any further copy or
        '''copies, of the virus (that may be) hidden, in other folders!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FindCloneButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FindCloneButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use to get full file or folder details.  You can find
        '''specific types of files, with non-standard attributes..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FolderInfoButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FolderInfoButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gives user, back control of the Windows® Folder Options. 
        '''
        '''Using this button, starts Windows® Folder Options Window..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_FolderOptionsButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_FolderOptionsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generates a current, running processes list.
        '''
        '''Which is then displayed, in Windows® Notepad. 
        '''
        '''This allows you to track &amp; trace any errant or
        '''&apos;nasty&apos; processes, that should NOT be there!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_GenerateprocessListButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_GenerateprocessListButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displays, the current drive properties..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_GetdrvProperty() As String
            Get
                Return ResourceManager.GetString("hlpcFA_GetdrvProperty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detects ALL removable media ( i.e. Pen Drive) connected to OS..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_GetRemovalMedia() As String
            Get
                Return ResourceManager.GetString("hlpcFA_GetRemovalMedia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selects the V.E.R.© colour theme..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_GroupBox12() As String
            Get
                Return ResourceManager.GetString("hlpcFA_GroupBox12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can run any program(s) from here. This is
        '''similar to, the New Task option in Task Manager..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_GroupBox8() As String
            Get
                Return ResourceManager.GetString("hlpcFA_GroupBox8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tick to disable, the bubble-help tool-tips..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Help_box() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Help_box", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send To Tray &amp; Minimize, V.E.R.© then moves to
        '''the background, ALL V.E.R.©&apos;s services &amp; scans..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_HideButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_HideButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hides drive(s) from Windows® Explorer &amp; V.E.R.©..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_HideDriveButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_HideDriveButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Any Autorun.inf file(s) present in CD or DVD will be ignored..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_IGN_CDROM() As String
            Get
                Return ResourceManager.GetString("hlpcFA_IGN_CDROM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.E.R.© will recursively Delete all files in all child folder(s)..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_IncSd1() As String
            Get
                Return ResourceManager.GetString("hlpcFA_IncSd1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.E.R.© will recursively Delete all files, with 
        '''the specified extension(s) in all child folders..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_IncSubDir2() As String
            Get
                Return ResourceManager.GetString("hlpcFA_IncSubDir2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows present Autorun.inf file, in each USB drive.
        '''
        '''Selecting these file(s) you can obtain information
        '''about, any associated processes and other file(s)..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_InfBox() As String
            Get
                Return ResourceManager.GetString("hlpcFA_InfBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kills the currently selected process. Or if more
        '''than just one process is ticked, kills all ticked..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_KillThis() As String
            Get
                Return ResourceManager.GetString("hlpcFA_KillThis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximize V.E.R.©. Make V.E.R.© fill current display..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_MaximizeButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_MaximizeButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this Button to obtain removable media detail.
        '''
        '''Using this button, you can unHide any virus files, etc.
        '''Which may be a virus, or viral-like in their activities..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_MediaInfoButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_MediaInfoButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimizes V.E.R.© To the Windows® Taskbar..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_MinimizeButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_MinimizeButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display associated module(s) with the current selected process..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ModuleList() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ModuleList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run the, (OS) System Information Tool.
        '''
        '''Note: Not installed in all Windows® OSes!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_MSInfoButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_MSInfoButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this, and you can Delete all the shown file(s)
        '''and any associated processes (to it) with one click..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_onehit() As String
            Get
                Return ResourceManager.GetString("hlpcFA_onehit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show ALL files, in current selected path, 
        '''with both System + Hidden attributes set..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_OnlySystemHidden() As String
            Get
                Return ResourceManager.GetString("hlpcFA_OnlySystemHidden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.E.R.© configuration, and it&apos;s RUNNING options area..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_OptionButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_OptionButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Command Line of a process, is the run
        '''or loading instruction, for that process..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ProcessCommandLine() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ProcessCommandLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display complete details of currently selected process..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ProcessDetailList() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ProcessDetailList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This list will display all processes using file, 
        '''with the same name..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ProList() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ProList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When you click on this Button, V.E.R.© will then
        '''create a special protected folder named &quot;AutoRun.inf&quot;
        '''on your USB drive(s) &amp; your hard-drive(s) partitions.
        '''
        '''Prevents future infections, of the Autorun.inf type..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Protectdrive() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Protectdrive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sends all Deleted file(s), to the Windows® Recycle Bin.
        '''
        '''Note :
        '''Sending file(s) to Recycle bin is a time consuming process.
        '''This could or likely will take additional time to complete!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_RecycleBinBox() As String
            Get
                Return ResourceManager.GetString("hlpcFA_RecycleBinBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.E.R.© will Delete any empty folder, if found at current location..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_REDir1() As String
            Get
                Return ResourceManager.GetString("hlpcFA_REDir1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refreshes the Virus Effect Remover© Status..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_RefreshButtonMain() As String
            Get
                Return ResourceManager.GetString("hlpcFA_RefreshButtonMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to remove files, with these attributes.
        ''' 
        '''This only Deletes &apos;S+H&apos; attribute files, ANY
        '''Hidden ONLY attribute files, are NOT Deleted!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_RemoveSystemHidden() As String
            Get
                Return ResourceManager.GetString("hlpcFA_RemoveSystemHidden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Renames the selected filename, to &quot;Renamed &quot;+&quot;Original filename.&quot;
        ''' 
        '''Warning! Use Caution! When renaming any files, are they needed?.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_RenameFileInList() As String
            Get
                Return ResourceManager.GetString("hlpcFA_RenameFileInList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some virus(s) modify the Internet Explorer Title Bar.
        '''Users can cure these changes, by using this button..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_RenameIEButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_RenameIEButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset(s) ALL Windows© default tools and win update!
        '''
        '''The vital tools in Windows® like regedit, taskmgr, 
        '''Cmd (Command Prompt etc.) &amp; AutoUpdate, are often 
        '''disabled by viruses or trojans deliberately!
        '''
        '''V.E.R.© fixes them for you! With just one Click!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Run_remover() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Run_remover", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The same as Windows® RUN command, runs despite virus or trojan!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_RunNewProcessButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_RunNewProcessButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Using this Tab you can rescan any process and it&apos;s
        '''associated files. If you think, it may be a virus..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_scanagain() As String
            Get
                Return ResourceManager.GetString("hlpcFA_scanagain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This lists ALL the running services/processes in your OS..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ScanServiceButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ScanServiceButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scans, and then lists ALL the Startup items in your OS..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ScanStartupButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ScanStartupButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set the V.E.R.© background Refresh time interval..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ScanTime() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ScanTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provides you the authority to modify NTFS file permissions,
        '''of files or folders. For Very ADVANCED* Windows users only!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_SecurityPermissionsButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_SecurityPermissionsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This sends V.E.R.© application to background at startup..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_send2tray() As String
            Get
                Return ResourceManager.GetString("hlpcFA_send2tray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click Button. To RUN the Windows® System File Checker.
        '''                                    
        '''IMPORTANT NOTE: You MUST have your MASTER Windows®XP
        '''Installation (Holographic LOGOed ) CD/DVD to run this.
        '''
        '''For more details on (sfc.exe) see PDF or Help file..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_SFC() As String
            Get
                Return ResourceManager.GetString("hlpcFA_SFC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows ALL files, in the current selected path..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ShowAllFile() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ShowAllFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show ALL files in selected path, with Hidden attribute set..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ShowAllHiddenFile() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ShowAllHiddenFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show ALL files in selected path, with System attribute set..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ShowAlllSytemFile() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ShowAlllSytemFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to open the Windows© OS Folder Options.
        ''' 
        '''Use this button, if you suspect that your OS
        '''Folder Options, might have been disabled..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ShowFolderOption() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ShowFolderOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show any Hidden Files and Folders..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_ShowHideFile() As String
            Get
                Return ResourceManager.GetString("hlpcFA_ShowHideFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows you ALL suspicious files in your O/System folders.
        '''
        '''Carefully, check any .bat, .cmd, .com, .dll, &amp; .exe, files.
        '''Check online, any of the above, could be a virus infection!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_Sys_Hidden_Show() As String
            Get
                Return ResourceManager.GetString("hlpcFA_Sys_Hidden_Show", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show any System + Hidden Files and Folders..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_SystemHided() As String
            Get
                Return ResourceManager.GetString("hlpcFA_SystemHided", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can Unlock any module, associated with a process,
        '''even, WITHOUT terminating, that process itself..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_UnlockModuleButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_UnlockModuleButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toggle on/off, the detection of ANY OS USB storage device.
        '''
        '''Useful to prevent others, from infecting your Windows® OS..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_USBStorageDeviceOption() As String
            Get
                Return ResourceManager.GetString("hlpcFA_USBStorageDeviceOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Viruses HIDE using the OS Hidden+System attributes.
        ''' 
        '''Click this button to REVEAL ANY such &apos;S+H&apos; files,
        '''if ANY file appears, and then disappears again.
        '''
        '''Then YOU KNOW it&apos;s a virus &amp; &quot;Live &amp; Active&quot; in OS!.
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_VisualiseAllFile() As String
            Get
                Return ResourceManager.GetString("hlpcFA_VisualiseAllFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run the V.E.R.© Windows Cleaner tool..
        '''</summary>
        Public Shared ReadOnly Property hlpcFA_WCleanButton() As String
            Get
                Return ResourceManager.GetString("hlpcFA_WCleanButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allows you authority, to edit Group Policy Objects,
        '''which can be linked to a Site, Domain, or Organisation 
        '''Unit, in the Active folder, or stored on a computer..
        '''</summary>
        Public Shared ReadOnly Property hlptFA_GroupPolicyEditerToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("hlptFA_GroupPolicyEditerToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click, to make a partial - Registry backup.
        '''
        '''Note: It only stores SOME sensitive registry data,
        '''in a special type of backup file, only for V.E.R.©..
        '''</summary>
        Public Shared ReadOnly Property hlptFA_MakeRegisrtyBackupToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("hlptFA_MakeRegisrtyBackupToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore previous Partial - Registry backup to optimal.
        '''
        '''Note: Restores only SOME special registry data, back
        '''that you backed up, with the V.E.R.© Registry backup..
        '''</summary>
        Public Shared ReadOnly Property hlptFA_RestoreBackupToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("hlptFA_RestoreBackupToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continous scanning of floppy drive(s) is both time consuming, and could damage
        '''the floppy drive-head. For this reason... V.E.R.© ONLY SCANS THE FLOPPY ONCE!
        '''At the start and loading of V.E.R.©, this is to protect the floppy drive head!
        '''
        '''We recommend that you add, any floppy drive(s) to V.E.R.©&apos;s Ignore Drive List.
        '''
        '''Would you like to add floppy drive(s) to the V.E.R.© Ignore List, now?
        '''.
        '''</summary>
        Public Shared ReadOnly Property MainFloppyMsg() As String
            Get
                Return ResourceManager.GetString("MainFloppyMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File does not exist..
        '''</summary>
        Public Shared ReadOnly Property msg_FileDoesNotExist() As String
            Get
                Return ResourceManager.GetString("msg_FileDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder does not exist..
        '''</summary>
        Public Shared ReadOnly Property msg_FolderDoesNotExist() As String
            Get
                Return ResourceManager.GetString("msg_FolderDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path does not exist..
        '''</summary>
        Public Shared ReadOnly Property msg_PathDoesNotExist() As String
            Get
                Return ResourceManager.GetString("msg_PathDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are now trying to disable Process filter.
        '''This will NOT protect you from system termination.
        '''
        '''We strongly recommend that you, ENABLE Process filter!
        '''Despite our recommendation, do you still want to disable, Process filter?.
        '''</summary>
        Public Shared ReadOnly Property msgEnableProcessFilter() As String
            Get
                Return ResourceManager.GetString("msgEnableProcessFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continous scanning of floppy drive(s) is both time consuming, and could damage
        '''the floppy drive-head. For this reason... V.E.R.© ONLY SCANS THE FLOPPY ONCE!
        '''At the start and loading of V.E.R.©, this is to protect the floppy drive head!
        '''
        '''We recommend that you to ignore, any floppy drive(s).
        '''
        '''Would you like to add floppy drive(s) to the V.E.R.© Scan List, now?.
        '''</summary>
        Public Shared ReadOnly Property msgFloppyCheckbox() As String
            Get
                Return ResourceManager.GetString("msgFloppyCheckbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''----------------------------------------------------------------------------
        '''.
        '''</summary>
        Public Shared ReadOnly Property Seperator() As String
            Get
                Return ResourceManager.GetString("Seperator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
